language: node_js
node_js:
- stable
branches:
  except:
    - gh-pages
deploy:
  provider: npm
  email: theisen.sanders@gmail.com
  api_key:
    secure: GEm30p0D07lW7lIJYbbM7vetXJjtIRWJvLR+RhMDgNnZighmyoUjWmD5E/62HUzGj7w7lHoM4DPWpRbUJj8phFNrsuajRAfep0+yy36+jvaCzvPs0bJZTSfdCdKXiWCJH75WKh0rU4NfDLvJylUZoqcyj7REBxCDM/r5tduUqUo421AJ3n8EJU7WhaqcS5CGFGYgaorhyHOXSh2szZq6mGobnrpEN3sm52T48ehK8YEdwb5wv67UQF6jTTM8BhrgZcH9UoneDUA1AciX/rh2IWoTS9Jb6RjRM8+C6ZL6kDaGpuMNsphROgAwGkDOvglg7xIHedtWHbEs+lmwXXXX5DzWohcu6bzM6Sz8CzGXQARxHJRQS+87PMPjZ8xYWAOlV3Qi8RiHLsXnOzpF0eU84/q9AKLptf+RyWcPX6J6G0xElKPcFgp4ojpMB7Eutn5CR0iphzgA6XS4i+ByaX7k0A7z+iMrmKG6ms76JOqGMiVjluNP0V2+vKLuIMXw3t1SiCevSw+GoFskPL0TK/2ZBTcWE//QyRNgLds17iRzNHawdwiqY3L2N31bShge9dlpp3KhvlLkme2EVkbATnbCPwSp5IvexAcOOJDqK+6mmQ9HPKWZ95AN6jq6hQl5R4L5bkUBIdne4LYaOAxh18y2arzFl86ufyjhybixMkbctT0=
  on:
    tags: true
    repo: trsanders/responsive-sketchpad
