name: Node.js Build
on:
  push:
  schedule:
    - cron:  '0 14 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm test
      - run: npm pack && tar -xvzf *.tgz && rm *.tgz

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: package/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: package

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - run: npm publish package --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
